services:

  client:
    build:
      context: ./client/.
    ports:
      - 3300:80
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/share/nginx/html

  server:
    build:
      context: ./server/.
    ports:
      - 8080:8080
